# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper', '0002_auto_20171104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
