# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper', '0003_treatment_carbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='owner',
        ),
    ]
