# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper', '0004_remove_treatment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='BG',
        ),
        migrations.AddField(
            model_name='treatment',
            name='bg',
            field=models.IntegerField(default=80, verbose_name='BG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dose',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Insulin dose'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='meal',
            field=models.CharField(max_length=25),
        ),
    ]
